# Generated by Django 4.2.8 on 2023-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Статья')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
